language: c

sudo: required

env:
  - PG_VERSION=9.3
  - PG_VERSION=9.4
  - PG_VERSION=9.5

before_script:
  - sudo apt-get install postgresql-server-dev-$PG_VERSION
  - sudo apt-get install postgresql-common

script:
  - make installcheck
